# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fvizcaya <fvizcaya@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/03/26 12:02:18 by fvizcaya          #+#    #+#              #
#    Updated: 2024/04/01 18:15:43 by fvizcaya         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC = clang
CFLAGS = -Wall -Wextra -Werror
LIB_PATH = ../libft.a
SUBFIX = _main.c

atoi:
	$(CC) $(CFLAGS) atoi$(SUBFIX) $(LIB_PATH)
	
bzero:
	$(CC) $(CFLAGS) bzero$(SUBFIX) $(LIB_PATH)

calloc:
	$(CC) $(CFLAGS) calloc$(SUBFIX) $(LIB_PATH)
	
itoa:
	$(CC) $(CFLAGS) itoa$(SUBFIX) $(LIB_PATH)
	
memchr:
	$(CC) $(CFLAGS) memchr$(SUBFIX) $(LIB_PATH)

memcmp:
	$(CC) $(CFLAGS) memcmp$(SUBFIX) $(LIB_PATH)
	
memcpy:
	$(CC) $(CFLAGS) memcpy$(SUBFIX) $(LIB_PATH)

memmove:
	$(CC) $(CFLAGS) memmove$(SUBFIX) $(LIB_PATH)

memset:
	$(CC) $(CFLAGS) memset$(SUBFIX) $(LIB_PATH)

putnbr_fd:
	$(CC) $(CFLAGS) putnbr_fd$(SUBFIX) $(LIB_PATH)

putchar_fd:
	$(CC) $(CFLAGS) putchar_fd$(SUBFIX) $(LIB_PATH)

putendl_fd:
	$(CC) $(CFLAGS) putendl_fd$(SUBFIX) $(LIB_PATH)

putstr_fd:
	$(CC) $(CFLAGS) putstr_fd$(SUBFIX) $(LIB_PATH)

strdup:
	$(CC) $(CFLAGS) strdup$(SUBFIX) $(LIB_PATH)

strtrim:
	$(CC) $(CFLAGS) strtrim$(SUBFIX) $(LIB_PATH)

strchr:
	$(CC) $(CFLAGS) strchr$(SUBFIX) $(LIB_PATH)

strlcat:
	$(CC) $(CFLAGS) strlcat$(SUBFIX) $(LIB_PATH)

strlcpy:
	$(CC) $(CFLAGS) strlcpy$(SUBFIX) $(LIB_PATH)

strmapi:
	$(CC) $(CFLAGS) strmapi$(SUBFIX) $(LIB_PATH)
	
strnstr:
	$(CC) $(CFLAGS) strnstr$(SUBFIX) $(LIB_PATH)

strrchr:
	$(CC) $(CFLAGS) strrchr$(SUBFIX) $(LIB_PATH)

split:
	$(CC) $(CFLAGS) split$(SUBFIX) $(LIB_PATH)

substr:
	$(CC) $(CFLAGS) substr$(SUBFIX) $(LIB_PATH)
	
bonus:
	$(CC) $(CFLAGS) bonus$(SUBFIX) $(LIB_PATH)

